remove opposite routes

diff --git a/ansible/node-centos-routes.yaml b/ansible/node-centos-routes.yaml
--- a/ansible/node-centos-routes.yaml
+++ b/ansible/node-centos-routes.yaml
@@ -48,10 +48,9 @@
         echo "Route does not exit.  No need to delete {{ item.subnet }}"
       fi
     with_items:
-      - { subnet: "{{ private_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
-      - { subnet: "{{ public_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
-      - { subnet: "{{ vpn_cidr_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
-    when: envtier == 'prod'
+      - { subnet: "{{ private_subnet1 }}", next_hop: "{{ openfirehawkserver }}" }
+      - { subnet: "{{ public_subnet1 }}", next_hop: "{{ openfirehawkserver }}" }
+      - { subnet: "{{ vpn_cidr }}", next_hop: "{{ openfirehawkserver }}" }
     become: yes
     tags:
       - add-routes
@@ -60,10 +59,9 @@
     shell: |
       ip route add {{ item.subnet }} via {{ item.next_hop }} dev {{ ethernet_device }}
     with_items:
-      - { subnet: "{{ private_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
-      - { subnet: "{{ public_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
-      - { subnet: "{{ vpn_cidr_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
-    when: envtier == 'prod'
+      - { subnet: "{{ private_subnet1 }}", next_hop: "{{ openfirehawkserver }}" }
+      - { subnet: "{{ public_subnet1 }}", next_hop: "{{ openfirehawkserver }}" }
+      - { subnet: "{{ vpn_cidr }}", next_hop: "{{ openfirehawkserver }}" }
     become: yes
     tags:
       - add-routes
@@ -76,60 +74,104 @@
         {{ item.subnet }} via {{ item.next_hop }} dev {{ ethernet_device }}
       marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.subnet }}"
     with_items:
-      - { subnet: "{{ private_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
-      - { subnet: "{{ public_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
-      - { subnet: "{{ vpn_cidr_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
-    when: envtier == 'prod'
+      - { subnet: "{{ private_subnet1 }}", next_hop: "{{ openfirehawkserver }}" }
+      - { subnet: "{{ public_subnet1 }}", next_hop: "{{ openfirehawkserver }}" }
+      - { subnet: "{{ vpn_cidr }}", next_hop: "{{ openfirehawkserver }}" }
     become: yes
     tags:
       - add-routes
 
+  # - name: remove previous routes if they exist.  ignore errors if commmand fails - routes probably don't exist.
+  #   shell: |
+  #     ip route list | grep {{ item.subnet }}
+  #     if [ $? -eq 0 ]; then
+  #       ip route del {{ item.subnet }}
+  #     else
+  #       echo "Route does not exit.  No need to delete {{ item.subnet }}"
+  #     fi
+  #   with_items:
+  #     - { subnet: "{{ private_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
+  #     - { subnet: "{{ public_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
+  #     - { subnet: "{{ vpn_cidr_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
+  #   when: envtier == 'prod'
+  #   become: yes
+  #   tags:
+  #     - add-routes
 
-### configure dev routes
-  - name: remove previous routes if they exist.  ignore errors if commmand fails - routes probably don't exist.
-    shell: |
-      ip route list | grep {{ item.subnet }}
-      if [ $? -eq 0 ]; then
-        ip route del {{ item.subnet }}
-      else
-        echo "Route does not exit.  No need to delete {{ item.subnet }}"
-      fi
-    with_items:
-      - { subnet: "{{ private_subnet1_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
-      - { subnet: "{{ public_subnet1_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
-      - { subnet: "{{ vpn_cidr_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
-    when: envtier == 'dev'
-    become: yes
-    tags:
-      - add-routes
+  # - name: "add routes via vpn - prod - {{ variable_host }} - device {{ ethernet_device }}"
+  #   shell: |
+  #     ip route add {{ item.subnet }} via {{ item.next_hop }} dev {{ ethernet_device }}
+  #   with_items:
+  #     - { subnet: "{{ private_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
+  #     - { subnet: "{{ public_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
+  #     - { subnet: "{{ vpn_cidr_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
+  #   when: envtier == 'prod'
+  #   become: yes
+  #   tags:
+  #     - add-routes
 
-  - name: "add routes via vpn - dev - {{ variable_host }} - device {{ ethernet_device }}"
-    shell: |
-      ip route add {{ item.subnet }} via {{ item.next_hop }} dev {{ ethernet_device }}
-    with_items:
-      - { subnet: "{{ private_subnet1_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
-      - { subnet: "{{ public_subnet1_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
-      - { subnet: "{{ vpn_cidr_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
-    when: envtier == 'dev'
-    become: yes
-    tags:
-      - add-routes
+  # - name: insert/update block in /etc/network/interfaces for routes. configure routes to opposite dev/prod environment so that nodes in both envs can access licence server.  Remove route if it exists and re apply it.
+  #   blockinfile:
+  #     path: "/etc/sysconfig/network-scripts/route-{{ ethernet_device }}"
+  #     create: true
+  #     block: |
+  #       {{ item.subnet }} via {{ item.next_hop }} dev {{ ethernet_device }}
+  #     marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.subnet }}"
+  #   with_items:
+  #     - { subnet: "{{ private_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
+  #     - { subnet: "{{ public_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
+  #     - { subnet: "{{ vpn_cidr_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
+  #   when: envtier == 'prod'
+  #   become: yes
+  #   tags:
+  #     - add-routes
 
-  - name: insert/update block in /etc/sysconfig/network-scripts/route-{{ ethernet_device }} for routes for persistance after reboot
-    blockinfile:
-      path: "/etc/sysconfig/network-scripts/route-{{ ethernet_device }}"
-      create: true
-      block: |
-        {{ item.subnet }} via {{ item.next_hop }} dev {{ ethernet_device }}
-      marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.subnet }}"
-    with_items:
-      - { subnet: "{{ private_subnet1_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
-      - { subnet: "{{ public_subnet1_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
-      - { subnet: "{{ vpn_cidr_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
-    when: envtier == 'dev'
-    become: yes
-    tags:
-      - add-routes
+
+# ### configure dev routes
+#   - name: remove previous routes if they exist.  ignore errors if commmand fails - routes probably don't exist.
+#     shell: |
+#       ip route list | grep {{ item.subnet }}
+#       if [ $? -eq 0 ]; then
+#         ip route del {{ item.subnet }}
+#       else
+#         echo "Route does not exit.  No need to delete {{ item.subnet }}"
+#       fi
+#     with_items:
+#       - { subnet: "{{ private_subnet1_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
+#       - { subnet: "{{ public_subnet1_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
+#       - { subnet: "{{ vpn_cidr_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
+#     when: envtier == 'dev'
+#     become: yes
+#     tags:
+#       - add-routes
+
+#   - name: "add routes via vpn - dev - {{ variable_host }} - device {{ ethernet_device }}"
+#     shell: |
+#       ip route add {{ item.subnet }} via {{ item.next_hop }} dev {{ ethernet_device }}
+#     with_items:
+#       - { subnet: "{{ private_subnet1_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
+#       - { subnet: "{{ public_subnet1_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
+#       - { subnet: "{{ vpn_cidr_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
+#     when: envtier == 'dev'
+#     become: yes
+#     tags:
+#       - add-routes
+
+#   - name: insert/update block in /etc/sysconfig/network-scripts/route-{{ ethernet_device }} for routes for persistance after reboot
+#     blockinfile:
+#       path: "/etc/sysconfig/network-scripts/route-{{ ethernet_device }}"
+#       create: true
+#       block: |
+#         {{ item.subnet }} via {{ item.next_hop }} dev {{ ethernet_device }}
+#       marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.subnet }}"
+#     with_items:
+#       - { subnet: "{{ private_subnet1_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
+#       - { subnet: "{{ public_subnet1_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
+#       - { subnet: "{{ vpn_cidr_dev }}", next_hop: "{{ openfirehawkserver_dev }}" }
+#     when: envtier == 'dev'
+#     become: yes
+#     tags:
+#       - add-routes
 
 # this is potentially a disruptive operation if configuring in the middle of work, instead we test just adding the route immediately
   # - name: Restart network service
